name: Build and Install uddl Projects

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Runner environment (OS)
    steps:
      - uses: actions/checkout@v3
        # with:
        #   # Assuming you have a separate secret for your GitHub credentials named 'GITHUB_TOKEN'
        #   credentials: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up Maven
      #   uses: maven/maven-action@v3  # Action from GitHub Marketplace
      #   with:
      #     maven: '3.8.5'  # Specify desired Maven version (optional)

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: bankolejohn/uddl-1a
          
      - name: Build and install UDDL-Query
        run: mvn clean install -Djava.version=17  

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: bankolejohn/uddl-test
          
      - name: Build and install UDDL
        run: mvn clean install -Djava.version=17  

      # - name: Checkout UDDL-Query (Stage 1)
      #   run: git clone https://github.com/bankolejohn/uddl-1a.git

      # - name: Build and install UDDL-Query
      #   run: mvn clean install -Djava.version=17  # Leverage Maven action

      # - name: Checkout UDDL (Stage 2)
      #   run: git clone https://github.com/bankolejohn/uddl-test.git

      # - name: Build and install UDDL
      #   run: mvn clean install -Djava.version=17  # Leverage Maven action

      # - name: Checkout FACE (Stage 3)
      #   run: git clone https://github.com/bankolejohn/face-new.git

      # - name: Build and install FACE
      #   run: mvn clean install -Djava.version=17  # Leverage Maven action 
